version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: weekly
      time: "09:30"
      day: "wednesday"
      timezone: "Canada/Eastern"
    open-pull-requests-limit: 10